name: Main Workflow

on:
  push:
  pull_request:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  check-package-lock:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Check if package-lock.json is up to date
        run: npx --yes package-lock-utd@1.x.x

  build:
    needs: check-package-lock

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build all packages
        run: npm run build

  lint-and-test:
    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build the library
        run: npm run build -w=search-expression-parser

      - name: Run the linter
        run: npm run lint

      - name: Run the tests
        run: npm run test

  publish:
    if: github.event_name == 'release'
    needs: lint-and-test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          # For some reason, it is necessary to explicitly set a registry URL so that authentication works properly.
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm ci

      - name: Build the library
        run: npm run build -w=search-expression-parser

      - name: Copy the README file
        run: cp ./README.md ./packages/search-expression-parser/README.md

      - name: Publish the package
        run: npm publish -w=search-expression-parser
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  deploy-docs:
    # Make sure this does not run on forked repos. Also, only run this when pushing to our main branch.
    if: |
      github.repository == 'MBuchalik/search-expression-parser' 
      && github.ref == 'refs/heads/main'
      && github.event_name == 'push'

    needs: lint-and-test

    runs-on: ubuntu-latest

    # Set permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages.
    permissions:
      contents: read
      pages: write
      id-token: write

    # Allow one concurrent deployment.
    concurrency:
      group: 'deploy-docs'
      cancel-in-progress: true

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build all packages
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './packages/docs/dist/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
